### ISSUE TITLE
Update current RSpec tests to RSpec 3

### ISSUE THREAD

**Issue by kwilczynski** [chef/mixlib-versioning#12]
We want to update tests to conform with RSpec 3, thus take care of a lot of deprecation warnings about functionality and/or style used.

**Comment by kwilczynski** [comment]
@tas50 hi there! Did you happy to update to Rspec 3 as part of other changes?

**Comment by tas50** [comment]
Fixed in #20

**Comment by kwilczynski** [comment]
@tas50 thank you!
