### ISSUE TITLE
Add the pessimistic version operator (~>)

### ISSUE THREAD

**Issue by kwilczynski** [chef/mixlib-versioning#14]
It would be nice to be able to express a version constraint using the pessimistic operator. It would also be nice to have `satisfied_by?` method (like in the `Gem::Requirement` class).

**Comment by StuporHero** [comment]
Since the chef_client_updater cookbook relies on this library for parsing the version, this would be nice to have to pin the chef-client to a version like '~> 13.0' so we don't have to try to keep up with the latest patch for a given minor version.

**Comment by kwilczynski** [comment]
@StuporHero I can have a look, then. Are you in a rush?

**Comment by kwilczynski** [comment]
I had a look. The challenge here would that related to the fact, that we expect version to be given just as-is without any constraints and/or operators, and rely on objects interaction. In other words, at the moment it's not possible to pass version as e.g. `>= 1.0.1` or `~> 11.18.12`, etc., as it would cause a parsing to return `nil` for such value.

```ruby
chef (12.18.31)> require 'mixlib/versioning'
 => true
chef (12.18.31)> Mixlib::Versioning.parse('> 1.0.1')
 => nil
chef (12.18.31)> Mixlib::Versioning.parse('1.0.1')
 => #<Mixlib::Versioning::Format::OpscodeSemVer:0x3fd6a9cea15c @major=1, @minor=0, @patch=1, @prerelease=nil, @build=nil, @input="1.0.1">
chef (12.18.31)>
```

This is the only issue to solve, as other provisions needed to implement `~>` are there already, so we can already do comparison e.g. `~> 1.0.1` to be `>= 1.0.1` and `< 1.1`, since all the required values are available after parsing.

Worth adding is that handling of pre-release versions, etc., would be a challenge in its own right.

**Comment by schisamo** [comment]
It would be awesome if we supported constraints like chef-sugar does:
https://github.com/sethvargo/chef-sugar/blob/master/lib/chef/sugar/constraints.rb

**Comment by StuporHero** [comment]
@kwilczynski Was the feature added? There is no tie to a pull request. It's certainly old enough to be subject to cleanup, but I'm just curious.

**Comment by kwilczynski** [comment]
Hi @StuporHero, sorry to startle you.

I was just doing some housekeeping and closing old issues. Feel free to work on this if you want.
