### ISSUE TITLE
1.2.1 release requires >= ruby 2.2, which restricts older chef-client versions

### ISSUE THREAD

**Issue by gshively11** [chef/mixlib-versioning#25]
We're running chef-client `12.9.41`, which has an embedded ruby version of `2.1.8p440`. After releasing mixlib-versioning 1.2.1, our chef-client runs are failing with:

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of C:/opscode/chef/embedded/bin/gem install mixlib-install -q --no-rdoc --no-ri -v "~> 2.0" ----
STDOUT: 
STDERR: ERROR:  Error installing mixlib-install:
  mixlib-versioning requires Ruby version >= 2.2.
---- End output of C:/opscode/chef/embedded/bin/gem install mixlib-install -q --no-rdoc --no-ri -v "~> 2.0" ----
Ran C:/opscode/chef/embedded/bin/gem install mixlib-install -q --no-rdoc --no-ri -v "~> 2.0" returned 1
```

[This commit](https://github.com/chef/mixlib-versioning/commit/94ff1a0fb8d879874312a103fd51dfedd1706543#diff-0e462ff0527cae72a3c29be82a4d1c6bR16) is the culprit and ended up in the 1.2.1 release.

I'm not sure about the correct way to resolve this, but our workaround at the moment is to manually install mixlib-versioning 1.1.0 before using the chef-ingredient cookbook (which depends on mixlib-install, which depends on mixlib-versioning). It seems like there was a semver/dependency breakdown somewhere in that chain.

**Comment by schisamo** [comment]
1.2.2 has been published to Rubygems.org
https://rubygems.org/gems/mixlib-versioning/versions/1.2.2
